# Generated by Django 4.2.2 on 2023-06-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registered_data',
            new_name='registered_date',
        ),
    ]
